# Generated by Django 3.1.3 on 2020-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosturalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posturaltype', models.PositiveSmallIntegerField(choices=[(0, 'wrong'), (1, 'WALKING'), (2, 'WALKING_UPSTAIRS'), (3, 'WALKING_DOWNSTAIRS'), (4, 'SITTING'), (5, 'STANDING'), (6, 'LAYING')], default=1)),
            ],
        ),
    ]
